export enum WeaponName {
  ODIN = 'Odin',
  ARES = 'Ares',
  VANDAL = 'Vandal',
  BULLDOG = 'Bulldog',
  PHANTOM = 'Phantom',
  JUDGE = 'Judge',
  BUCKY = 'Bucky',
  FRENZY = 'Frenzy',
  CLASSIC = 'Classic',
  GHOST = 'Ghost',
  SHERIFF = 'Sheriff',
  SHORTY = 'Shorty',
  OPERATOR = 'Operator',
  GUARDIAN = 'Guardian',
  MARSHAL = 'Marshal',
  SPECTRE = 'Spectre',
  STINGER = 'Stinger',
  MELEE = 'Melee',
}
